# Generated by Django 6.0.3 on 2026-06-30 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('token_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('IP', 'In Progress'), ('C', 'Completed'), ('X', 'Cancelled')], default='W', max_length=2)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.patient')),
            ],
        ),
    ]
