# Generated by Django 6.0.7 on 2026-07-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pastdoctor_doctor_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastDoctor',
        ),
    ]
